apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadvglh3235-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadvglh3235-tenant-component
    app.kubernetes.io/part-of: loadvglh3235-tenant-app
  name: loadvglh3235-tenant-component
  namespace: loadvglh3235-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadvglh3235-tenant-component
    weight: null
status: {}
